version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: IBclassess-frontend
    ports:
      - "9048:9048"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_APP_NAME=${VITE_APP_NAME}
    restart: unless-stopped
    networks:
      - IBclassess-network

networks:
  crm-network:
    driver: bridge